# Gradle 构建内存
org.gradle.jvmargs=-Xmx4G

# ============ 构建信息（想改模组版本号，改这里） ============
minecraft_version=1.20.1
forge_version=47.4.10
minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)
loader_version_range=[47,)

# ============ 模组信息 ============
mod_id=floatingtext
mod_name=Floating Text
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.floatingtext
mod_authors=FloatingText Team

# ============ 映射 ============
mapping_channel=official
mapping_version=1.20.1
